### ISSUE TITLE
Random "egrep" or "grep -E" behaviour of bsdgrep with enabled ASLR

### ISSUE THREAD

**Issue by dmilith** [HardenedBSD/hardenedBSD#204]
https://gist.github.com/dmilith/6475ce7870881f1d63b36ae978d876a4
or http://s.verknowsys.com/fd63fa3af0ad3c7eac54f19c4db1c636.png

Command:

echo '1.0.2' | grep -E '^1.0.[0-9]+$'

or

echo '1.0.2' | egrep '^1.0.[0-9]+$'

bsdgrep installed as main grep (WITH_BSD_GREP=1):

grep (BSD grep) 2.5.1-FreeBSD

uname -a
[1466844717] bh:/var/ServeD-OS λ uname -a
FreeBSD bh 11.0-ALPHA4-HBSD FreeBSD 11.0-ALPHA4-HBSD #10: Fri Jun 24 02:47:49 CEST 2016     root@bh:/usr/obj/usr/src/sys/VERKNOWSYS  amd64

**Comment by dmilith** [comment]
Problem dissapears right after: `sysctl hardening.pax.aslr.status=1`

**Comment by lattera** [comment]
This bug is due to the shared library load order randomization feature (called shlibrandom. As a workaround, you can add a secadm rule. In the near future, I plan to revamp shlibrandom to prevent issues like this from popping up. The revamp will also allow us to drop the only kernel<->userland ABI breakage we have in HardenedBSD.

**Comment by lattera** [comment]
Once commit 1b291848bfbb8fe12b893d12c5163f74b84257aa is MFC'd, I'll mark this ticket as closed. Ticket #188 will be the follow-up ticket for shlibrandom version 2.
