### ISSUE TITLE
system unreachable under heavy load with fpudna: fpcurthread == curthread

### ISSUE THREAD

**Issue by heraklit256** [HardenedBSD/hardenedBSD#307]
I am running HardenedBSD 11 (latest version) on a machine which is sometimes under heavy load. Sooner or later, it becomes instable, writing a bunch of

    [24450] fpudna: fpcurthread == curthread

messages to the dmesg log. Although the system seems to be still running, it cannot be accessed via remote network any more.

Output of `uname -a`:

    FreeBSD machine 11.2-PRERELEASE-HBSD FreeBSD 11.2-PRERELEASE-HBSD #0 : Thu Jun 14 03:31:14 UTC 2018     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD  amd64

Thanks in advance!

**Comment by heraklit256** [comment]
It turned out that the system (and all services) are still running, but network is unreachable.
Executing

    ifconfig [network interface] down
    ifconfig [network interface] up

seems to bring the system back to a normal state. Restarting `pf` accomplishes nothing.
Since I am flying blind here, any help is appreciated.

**Comment by utrenkner** [comment]
I get the same warnings in /var/log/messages, e.g.
```
Jun 20 08:46:29 <servername> kernel: [86772] fpudna: fpcurthread == curthread
```
I have not yet seen network downtimes in connection with this warning. The jailed web server continues working normally, according to the access logs. 

However, we had yesterday an *unexplained* issue with the daily sending of a newsletter, which is sent out by a PHP script and OpenSMTPD but which stopped after ca. 3/4 of the mails were sent out. This is the first time it happened, so it may or may not be connected to the same issue.

The server runs the latest 11.2-PRERELEASE-HBSD and the problems started after hbsd-update'ing last Sunday. The cause is almost certainly the [new FPU-vulnerability mitigation](https://github.com/HardenedBSD/hardenedBSD/commits/hardened/current/master/sys/amd64/amd64/fpu.c).

Can this be reverted until the problems are ironed out?

**Comment by utrenkner** [comment]
Should the FreeBSD devs who are working on the FPU issue be involved. Maybe we can help them identify remaining problems?

**Comment by lattera** [comment]
HardenedBSD has made no changes in 11-STABLE for the past few months. Can this be reproduced on FreeBSD? Or, can you provide me with reproduction steps?

**Comment by opntr** [comment]
False. The recent lazyfpu introduced this warning line.

Once I get back my Internet connection, I cut a new stable release.

**Comment by lattera** [comment]
> False

What is this in relation to? My comment that HardenedBSD has made no changes in 11-STABLE for the past few months? That's a true statement.

The last change introduced by HardenedBSD in 11-STABLE was a commit in April that re-introduces SIGINFO to setfacl (commit hash: bb86116a31f578d31a24373597b63d689b5216c2). I doubt that has any relation to this particular bug.

Another commit would be back in April, performing an MFC of FreeBSD's version of retpoline support (commit hash: 610cfa850332237f8a9cc8092ecb1eba991c2f2f). I doubt that would be the culprit.

There's more HBSD MFC's, but those are even earlier. This particular bug report has something to do with ([previously installed update] - [latest update]). I'm (somewhat naively) assuming [previously installed update] is after commit 3f1e0209bf5f8c4544b26517cea0705a2fd2d501, which happened in January 2018, which bumped __HardenedBSD_version to 1100055.

**Comment by lattera** [comment]
Perhaps we're running into a language barrier?

**Comment by utrenkner** [comment]
According to this [FreeBSD bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=229177), the problem is solved (trivially) by [removing the info](https://svnweb.freebsd.org/base?view=revision&revision=335131).

Of course, this does not explain the connectivity problems reported by @heraklit256.

**Comment by heraklit256** [comment]
My problem seems to be somehow to the `em` network driver. After switching to a `vtnet` interface, I still get lots of `fpudna: fpcurthread == curthread` messages, but connection seems to be more stable now.

However, there was an unexplained outage tonight which needs further investigation.

The problem occurred ~ 12 hours after updating to the latest HardenedBSD release, so I guess it has something to do with that.

**Comment by opntr** [comment]
Hi all!

Is this issue still a problem?

**Comment by utrenkner** [comment]
I never had those networking problems, only the warning message conc. fpudna. And they are gone since the latest 11-STABLE version (the one with OpenSSL in base).

**Comment by heraklit256** [comment]
I did not experienced the connectivity problems since systems moved to different network interface.
Closing this issue; if they still appear, it will be reopened.
