### ISSUE TITLE
Default IGNORE_OSVERSION to true, for automated installs

### ISSUE THREAD

**Issue by mcandre** [HardenedBSD/hardenedBSD#368]
By default, pkg update prompts the user to install potentially incompatible package updates, including in HardenedBSD 12. The prompt encourages the user to define a clear policy on this with the `IGNORE_OSVERSION` configuration variable. Maybe default this to `true` in the future?

Alternatively, I wonder if we could we provide a `skip` value for `IGNORE_OSVERSION`, so that incompatible versions are automatically excluded? This would helps automated scripts to run better, instead of having to choose between manual intervention on the one hand and potentially broken packages on the other.

Workaround:

```console
$ sudo sh -c "echo 'IGNORE_OSVERSION=true;' >>/usr/local/etc/pkg.conf"
```

**Comment by lattera** [comment]
Our package builder is paused at the moment due to infrastructure upgrades. I plan to kick off a new 12-stable/amd64 package build either tonight or tomorrow. Once the build completes (around 75 hours after it starts), secadm-kmod should match the kernel of the latest published 12-stable/amd64 release.

**Comment by lattera** [comment]
Closing this issue out. The package repos are now in a stable state.
